### ISSUE TITLE
fix: MainActivity image trying to draw too large

### ISSUE THREAD

**Issue by Maskeit** [PI5-Localito/Localito-Android#11]
**Describe the bug**

The error is that when starting it tries to draw the png image (bitmap) that is too large and exceeds the acceptable limits
**To Reproduce**
1. Start application
In the activity_main.xml
...
app:srcCompat="@drawable/market" -> it should be a **svg** not a **png**
...

**Screenshots**
![image](https://github.com/PI5-Localito/Localito-Android/assets/102250333/c1ed301c-392b-49d7-be64-dd3f344ab64d)

**Comment by ximenamzo** [comment]
@Maskeit I replicate the steps to see the bug but I see nothing related even in the logcat. Anyway, I'm currently changing the png for a svg file deleting the first one.
